### ISSUE TITLE
R shouldn't crash when accidentally accessing a PopsNetwork object after session reload

### ISSUE THREAD

**Issue by mhinsch** [mhinsch/rpathsonpaths#5]
There's unfortunately no simple solution for this (AFAICT external pointers are *not* set to zero on reload).

**Comment by thibautjombart** [comment]
Yes, I think this is a fairly toxic thing to play with, at least at the moment, for the reasons discussed before. I don't think we need to access the C++ data representation from R. Processing an `epicontacts` object each time we need to should not be a problem at this stage, and if we ever play with ABC then we can still design it so that the conversion happens only once.

**Comment by mhinsch** [comment]
Turns out RCPP *does* (contrary to what I read) actually provide a way to check for valid pointers. So, no more crashing, pointers are still dead after reload, though.
